USERNAME = "testuser1"
PASSWORD = "Testpassword1!"
FIRSTNAME = "TestFirstName"
LASTNAME = "TestLastName"
EMAIL = "testuser@demoqa.com"
ADDRESS = "Test Address"
PERMANENT_ADDRESS = "Test Permanent Address"
